---
server:
  interface: "$local_interface:8080"
  addresses: ["$global_interface:8080", "$local_interface:8080"]

service_locator:
  address: $service_locator_address
  username: web_portal_service
  password: $admin_password
...
