---
server:
  interface: local_interface:20600
  addresses: [global_address:20600, local_interface:20600]

service_locator:
  address: local_interface:20000
  username: risk_service
  password: admin_password

#session_start_time: 2013-10-31 00:00:00
...
