---
registry_server:
  interface: "$local_interface:20300"
  addresses: ["$global_address:20300", "$local_interface:20300"]

feed_server:
  interface: "$local_interface:20400"
  addresses: ["$global_address:20400", "$local_interface:20400"]

data_store:
  address: $mysql_address
  username: $mysql_username
  password: $mysql_password
  schema: market_data

countries:
  - AU
  - CA
  - HK
  - JP
  - US

service_locator:
  address: $service_locator_address
  username: market_data_service
  password: $admin_password
...
