---
source:
  address: local_interface:20000
  username: market_data_feed
  password: admin_password

target:
  address: local_interface:20000
  username: market_data_feed
  password: admin_password

bbo_partitions: 1
book_quote_partitions: 1
market_quote_partitions: 1
time_and_sale_partitions: 1
sampling: 100ms

symbols: [
  ABX.TSX,
  MSFT.NSDQ]
...
