---
service_locator:
  address: local_interface:20000
  username: market_data_feed
  password: admin_password

data_store: market_data.db
sampling: 100ms
start_time: 2018-06-18 19:00:00
client_count: 40
...
