---
server:
  interface: $local_interface:21900
  addresses: [$global_address:21900, $local_interface:21900]

data_store:
  address: $mysql_address
  username: $mysql_username
  password: $mysql_password
  schema: $mysql_schema

service_locator:
  address: $service_locator_address
  username: compliance_service
  password: $admin_password
...
