---
service_locator:
  address: $service_locator_address
  username: $username
  password: $admin_password

enable_logging: false
market: XNAS
sampling: 100ms
host: 233.46.176.5:55635
interface: $local_interface:55635

market_codes:
  - code: A
    market: XASE
  - code: B
    market: XBOS
  - code: C
    market: XCIS
  - code: D
    market: XADF
  - code: I
    market: XISX
  - code: J
    market: EDGA
  - code: K
    market: EDGX
  - code: M
    market: XCHI
  - code: N
    market: XNYS
  - code: P
    market: ARCX
  - code: Q
    market: XNAS
  - code: V
    market: IEXG
  - code: W
    market: XCBO
  - code: X
    market: XPHL
  - code: Y
    market: BATY
  - code: Z
    market: BATS
...
