---
service_locator:
  address: $service_locator_address
  username: $username
  password: $password

enable_logging: false
market: TSXV
sampling: 100ms
host: 224.0.72.15:30700
interface: $local_interface:30700
...
