---
service_locator:
  address: local_interface:20000
  username: market_data_feed
  password: admin_password

enable_logging: false
market: TSXV
sampling: 100ms
host: 224.0.72.15:30700
interface: local_interface:30700
...
