---
service_locator:
  address: $service_locator_address
  username: $username
  password: $admin_password

enable_logging: false
use_broker_number: false
mpid: CX2
consolidate_mpids: true
market: CX2
sampling: 100ms
enable_retransmission: false
max_retransmissions: 10000
retransmission_block_size: 20000
host: "233.102.209.244:61019"
interface: "$local_interface:61019"
retransmission_request_address: "142.201.149.44:61028"
retransmission_response_address: "142.201.149.44:61066"
...
