---
service_locator:
  address: local_interface:20000
  username: market_data_feed
  password: admin_password

enable_logging: false
mpid: CHIC
use_broker_number: false
consolidate_mpids: true
market: CHIC
sampling: 100ms
enable_retransmission: false
max_retransmissions: 10000
retransmission_block_size: 20000
host: 233.102.209.225:60002
interface: local_interface:60002
retransmission_request_address: 142.201.149.44:60021
retransmission_response_address: 142.201.149.44:60052
...
