---
service_locator:
  address: local_interface:20000
  username: market_data_feed
  password: admin_password

enable_logging: false
market: ASX
is_time_and_sale: true
sampling: 100ms
host: 233.71.185.11:21004
interface: 192.168.0.120:21004
glimpse_host: 203.0.119.213:21804
glimpse_timeout: 5s
username: glimpse_username
password: glimpse_password
...
