---
service_locator:
  address: $service_locator_address
  username: $username
  password: $admin_password

enable_logging: false
market: TSX
is_time_and_sale: true
sampling: 100ms
enable_retransmission: false
max_retransmissions: 10000
retransmission_block_size: 20000
host: 233.102.209.221:61110
interface: $local_interface:61110
retransmission_request_address: 142.201.149.36:61112
retransmission_response_address: 142.201.149.36:61113
...
