---
order_data_store:
  schema: spire
  address: 127.0.0.1
  username: spireadmin
  password: 1234

compliance_data_store:
  schema: spire
  address: 127.0.0.1
  username: spireadmin
  password: 1234
...
