---
service_locator:
  address: $service_locator_address
  username: $username
  password: $password

enable_logging: false
market: CXA
disseminating_market: CXA
mpid: CXA
time_zone: Australian_Eastern_Standard_Time 
is_time_and_sale: true
sampling: 100ms
host: 233.218.133.51:16001
interface: $local_interface:16001
...
