---
service_locator:
  address: local_interface:20000
  username: market_data_feed
  password: admin_password

enable_logging: false
market: TSX
is_time_and_sale: true
sampling: 100ms
enable_retransmission: false
max_retransmissions: 10000
retransmission_block_size: 20000
host: 233.102.209.232:60016
interface: local_interface:60016
retransmission_request_address: 142.201.149.36:60028
retransmission_response_address: 142.201.149.36:60068
...
