---
server:
  interface: local_interface:20200
  addresses: [global_address:20200, local_interface:20200]

service_locator:
  address: local_interface:20000
  username: definitions_service
  password: admin_password

minimum_spire_version: "1"
ntp_pool: [0.pool.ntp.org:123,
           1.pool.ntp.org:123,
           2.pool.ntp.org:123,
           3.pool.ntp.org:123]
countries: countries.yml
currencies: currencies.yml
destinations: destinations.yml
markets: markets.yml
time_zones: ./date_time_zonespec.csv
exchange_rates:
  - symbol: USD/CAD
    rate: 1.31
  - symbol: USD/AUD
    rate: 1.46
  - symbol: AUD/CAD
    rate: 0.90
  - symbol: HKD/CAD
    rate: 0.17
  - symbol: HKD/USD
    rate: 0.13
  - symbol: HKD/AUD
    rate: 0.19
...
