---
server:
  interface: local_interface:20700
  addresses: [global_address:20700, local_interface:20700]

service_locator:
  address: local_interface:20000
  username: order_execution_service
  password: admin_password

data_store:
  username: spireadmin
  password: admin_password
  schema: spire
  address: 127.0.0.1:3306
...
