---
server:
  interface: "$local_interface:20700"
  addresses: ["$global_address:20700", "$local_interface:20700"]

data_store:
  address: $mysql_address
  username: $mysql_username
  password: $mysql_password
  schema: $mysql_schema

service_locator:
  address: $service_locator_address
  username: order_execution_service
  password: $admin_password
...
