---
server:
  interface: "$local_interface:20100"
  addresses: ["$global_interface:20100", "$local_interface:20100"]

data_store:
  address: $mysql_address
  username: $mysql_username
  password: $mysql_password
  schema: $mysql_schema

service_locator:
  address: $service_locator_address
  username: administration_service
  password: $admin_password

organization: "Spire Trading Inc."

entitlements:
  - name: Demo Entitlements
    price: 0.00
    currency: USD
    group: demo_entitlements
    applicability:
      - source: ARCX
        messages: [BBO, BOOK, MQT, TAS, IMB]
      - source: BATS
        messages: [BBO, BOOK, MQT, TAS, IMB]
      - source: CHIC
        messages: [BBO, BOOK, MQT, TAS, IMB]
      - source: LYNX
        messages: [BBO, BOOK, MQT, TAS, IMB]
      - source: NEOE
        messages: [BBO, BOOK, MQT, TAS, IMB]
      - source: OMGA
        messages: [BBO, BOOK, MQT, TAS, IMB]
      - source: PURE
        messages: [BBO, BOOK, MQT, TAS, IMB]
      - source: XASE
        messages: [BBO, BOOK, MQT, TAS, IMB]
      - source: XATS
        messages: [BBO, BOOK, MQT, TAS, IMB]
      - source: XASX
        messages: [BBO, BOOK, MQT, TAS, IMB]
      - source: XCNQ
        messages: [BBO, MQT, BOOK, TAS, IMB]
      - source: XCX2
        messages: [BBO, MQT, BOOK, TAS, IMB]
      - source: XHKG
        messages: [BBO, MQT, BOOK, TAS, IMB]
      - source: XNAS
        messages: [BBO, BOOK, MQT, TAS, IMB]
      - source: XNYS
        messages: [BBO, BOOK, MQT, TAS, IMB]
      - source: XTSE
        messages: [BBO, BOOK, MQT, TAS, IMB]
      - source: XTSE
        messages: [BBO, BOOK, MQT, TAS, IMB]
...
